ETourGuide/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETourGuide.Models
{
    public class Answer
    {
        public int Id { get; set; }
        public string Statement { get; set; }
        public int QuestionId { get; set; }
        public Question Question { get; set; }
    }
}

ETourGuide/ViewModels/AnswersViewModel.cs
using ETourGuide.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETourGuide.ViewModels
{
    public class AnswersViewModel
    {
        public int QuestionId { get; set; }
        public IEnumerable<Question> Questions { get; set; }
        public string Statement { get; set; }
    }
}

ETourGuide/Areas/Admin/Controllers/AnswersController.cs
using ETourGuide.Models;
using ETourGuide.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETourGuide.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AnswersController : Controller
    {
        private ApplicationDbContext _context;

        public AnswersController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Admin/Answers
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            var questions = _context.Questions.ToList();

            var AnswersModel = new AnswersViewModel
            {
                Questions = questions
            };
            return View(AnswersModel);
        }

        public ActionResult Save(AnswersViewModel answers)
        {
            var answer = new Answer
            {
                QuestionId = answers.QuestionId,
                Statement = answers.Statement
            };

            _context.Answers.Add(answer);
            _context.SaveChanges();

            return RedirectToAction("Index","Questionnaire");
        }
    }
}

ETourGuide/Areas/Admin/Views/Answers/Add.cshtml
@model ETourGuide.ViewModels.AnswersViewModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                @using (Html.BeginForm("Save", "Answers", FormMethod.Post, new { @class = "add-place-form", enctype = "multipart/form-data" }))
                {
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Add Answers for Questions</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                @Html.DropDownListFor(q => q.QuestionId, new SelectList(Model.Questions, "Id", "Statement"), "Select Question", new { @class = "form-control select2" })
                            </div>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-address-book"></i></span>
                                </div>
                                @Html.TextBoxFor(q => q.Statement, new { type = "text", @class = "form-control", placeholder = "Answer Statement" })
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary">
                                Add Answer for this Question
                            </button>
                        </div>
                    </div>
                }
                <!-- /.card-body -->
            </div>
        </div>
        <!--/.col (left) -->

    </div>
</section>

ETourGuide/Areas/Admin/Views/Answers/Index.cshtml
@model ETourGuide.ViewModels.AnswersViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}