ETourGuide/Models/Province.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETourGuide.Models
{
    public class Province
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ETourGuide/ViewModels/ProvincesViewModel.cs
using ETourGuide.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETourGuide.ViewModels
{
    public class ProvincesViewModel
    {
        public List<Province> Provinces{ get; set; }
        public List<Place> Places { get; set; }
    }
}

ETourGuide/Areas/Admin/Controllers/ProvincesController.cs
using ETourGuide.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETourGuide.Areas.Admin.Controllers
{
    public class ProvincesController : Controller
    {
        private ApplicationDbContext _context;

        public ProvincesController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Admin/Provinces
        public ActionResult Index()
        {
            var provinces = _context.Provinces.ToList();
            return View(provinces);
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Save(Province province)
        {
            _context.Provinces.Add(province);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ETourGuide/Controllers/ProvincesController.cs
using ETourGuide.Models;
using ETourGuide.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETourGuide.Controllers
{
    public class ProvincesController : Controller
    {
        private ApplicationDbContext _context;

        public ProvincesController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: /Provinces
        public ActionResult Index()
        {
            var provinces = _context.Provinces.ToList();
            var places = _context.Places.ToList();

            var provinceModel = new ProvincesViewModel
            {
                Places = places,
                Provinces = provinces
            };

            return View(provinceModel);
        }
    }
}

ETourGuide/Areas/Admin/Views/Provinces/Add.cshtml
@model ETourGuide.Models.Province

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm("Save","Provinces",FormMethod.Post,new { @class =""}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Province</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ETourGuide/Areas/Admin/Views/Provinces/Index.cshtml
@model IEnumerable<ETourGuide.Models.Province>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <h2>Places</h2>
    @Html.ActionLink("Add a Province", "Add", null, new { @class = "btn btn-success pull-right" })
    <div class="ver_gap"></div>
    <table class="table list-table places-table">
        <tr style="box-shadow:0px 2px 3px #aaa; background:#0099cc;color:#fff">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @*@Html.ActionLink("Add", "Add", null, new { @class = "btn btn-success btn-sm" })*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }

    </table>

</div>